export default {
  name:'experience',
  title:'Experience',
  type:'document',
  fields:[
          {name:'name',
             title:'name',
             type:'string'
          },
          {
              name:'company',
              title:'Company',
              type:'string'
          },
          {
              name:'desc',
              title:'Desc',
              type:'string'
          }
  ]
}